export const USERNAME_RE = /^[a-zA-Z0-9_-]{3,20}$/;

// Matches the DB trigger format: <base>_<8 hex chars>
const AUTO_GENERATED_RE = /_[0-9a-f]{8}$/i;

export function isAutoGeneratedUsername(username: string): boolean {
  return AUTO_GENERATED_RE.test(username);
}

const RESERVED_WORDS = [
  "admin",
  "moderateur",
  "moderator",
  "fondateur",
  "founder",
  "sifflet",
  "vartime",
  "arbitre",
  "support",
  "contact",
  "root",
  "system",
];

export function isReservedUsername(username: string): boolean {
  const lower = username.toLowerCase();
  return RESERVED_WORDS.some((word) => lower.includes(word));
}

export function generateUsernameSuggestions(email: string): string[] {
  const base = email.split("@")[0] ?? "joueur";
  const clean = base.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 12);
  const suffix = Math.floor(Math.random() * 900 + 100);
  return [clean, `${clean}_${suffix}`, `${clean}${suffix}`].filter((s) =>
    USERNAME_RE.test(s),
  );
}
