"use client";

import { useState, useEffect } from "react";
import { useSearchParams } from "next/navigation";
import { Pencil } from "lucide-react";
import { toast } from "sonner";
import Image from "next/image";
import { useTranslations } from "next-intl";
import { useBcp47 } from "@/lib/use-bcp47";
import { ProfileEditModal } from "./ProfileEditModal";
import { UsernameSetupModal } from "@/components/onboarding/UsernameSetupModal";
import { isAutoGeneratedUsername } from "@/lib/username";
import { track } from "@/lib/analytics";

type TeamInfo = { id: string; name: string; logo_url: string | null } | null;

const BORDER_RING_CLASSES: Record<string, string> = {
  gold: "ring-4 ring-yellow-400 shadow-[0_0_24px_rgba(234,179,8,0.6)]",
  neon: "ring-4 ring-green-400 shadow-[0_0_24px_rgba(74,222,128,0.6)]",
  inferno: "ring-4 ring-orange-500 shadow-[0_0_24px_rgba(249,115,22,0.6)]",
  elite: "ring-4 ring-purple-500 shadow-[0_0_24px_rgba(168,85,247,0.6)]",
};

function getBorderRingClass(assetUrl: string) {
  return BORDER_RING_CLASSES[assetUrl] ?? "ring-2 ring-white/20";
}

function getRankRing(rankLabel: string) {
  const t = rankLabel.toLowerCase();
  if (t.includes("boss"))
    return "ring-4 ring-yellow-400 shadow-[0_0_24px_rgba(234,179,8,0.5)]";
  if (t.includes("argent"))
    return "ring-4 ring-slate-400 shadow-[0_0_24px_rgba(148,163,184,0.4)]";
  if (t.includes("bronze"))
    return "ring-4 ring-amber-600 shadow-[0_0_24px_rgba(217,119,6,0.5)]";
  return "ring-2 ring-white/20";
}

function getXpProgress(
  xp: number,
  labels: { district: string; bronze: string; argent: string; boss: string },
): {
  level: string;
  pct: number;
  next: number;
} {
  if (xp >= 5000) return { level: labels.boss, pct: 100, next: 5000 };
  if (xp >= 2000)
    return {
      level: labels.argent,
      pct: Math.round(((xp - 2000) / 3000) * 100),
      next: 5000,
    };
  if (xp >= 500)
    return {
      level: labels.bronze,
      pct: Math.round(((xp - 500) / 1500) * 100),
      next: 2000,
    };
  return {
    level: labels.district,
    pct: Math.round((xp / 500) * 100),
    next: 500,
  };
}

function getTrustGradeCompact(
  score: number,
  labels: {
    elite: string;
    official: string;
    alert: string;
    yellow: string;
  },
) {
  if (score >= 200)
    return {
      icon: "🏅",
      label: labels.elite,
      color: "text-yellow-400 border-yellow-500/30 bg-yellow-500/10",
    };
  if (score >= 100)
    return {
      icon: "✅",
      label: labels.official,
      color: "text-green-400 border-green-500/30 bg-green-500/10",
    };
  if (score >= 50)
    return {
      icon: "⚡",
      label: labels.alert,
      color: "text-blue-400 border-blue-500/30 bg-blue-500/10",
    };
  return {
    icon: "⚠️",
    label: labels.yellow,
    color: "text-orange-400 border-orange-500/30 bg-orange-500/10",
  };
}

export function ProfileHeader({
  username: initialUsername,
  avatarUrl: initialAvatarUrl,
  favoriteTeam: initialTeam,
  rank,
  xpTotal,
  balance,
  loginStreak,
  lastLoginDate,
  trustScore,
  compact = false,
  preferredCompetitions = [],
  streakFreezesOwned = 0,
  equippedAvatarAsset,
  equippedBorderAsset,
  userEmail,
}: {
  username: string;
  avatarUrl: string | null;
  favoriteTeam: TeamInfo;
  karma?: { emoji: string; label: string; cls: string };
  rank: { emoji: string; label: string };
  xpTotal: number;
  balance: number;
  loginStreak?: number;
  lastLoginDate?: string | null;
  trustScore?: number;
  compact?: boolean;
  preferredCompetitions?: string[];
  streakFreezesOwned?: number;
  equippedAvatarAsset?: string | null;
  equippedBorderAsset?: string | null;
  userEmail?: string;
}) {
  const tp = useTranslations("Profile");
  const bcp47 = useBcp47();

  const [editOpen, setEditOpen] = useState(false);
  const [showUsernameModal, setShowUsernameModal] = useState(false);
  const searchParams = useSearchParams();

  useEffect(() => {
    if (searchParams.get("section") === "club") {
      const id = setTimeout(() => setEditOpen(true), 0);
      return () => clearTimeout(id);
    }
  }, [searchParams]);
  const [username, setUsername] = useState(initialUsername);
  const [avatarUrl, setAvatarUrl] = useState<string | null>(initialAvatarUrl);
  const [team, setTeam] = useState<TeamInfo>(initialTeam);
  const [claimingStreak, setClaimingStreak] = useState(false);
  const [streakClaimed, setStreakClaimed] = useState(() => {
    if (typeof window === "undefined") return false;
    const todayStr = new Date().toISOString().slice(0, 10);
    return lastLoginDate === todayStr;
  });

  const streak = loginStreak ?? 0;
  const canClaimStreak = streak > 0 && !streakClaimed;
  const avatar = equippedAvatarAsset ?? avatarUrl ?? "🎽";
  const ringCls = equippedBorderAsset
    ? getBorderRingClass(equippedBorderAsset)
    : getRankRing(rank.label);
  const xpInfo = getXpProgress(xpTotal, {
    district: tp("xpLevelDistrict"),
    bronze: tp("xpLevelBronze"),
    argent: tp("xpLevelArgent"),
    boss: tp("xpLevelBoss"),
  });
  const trust =
    trustScore != null
      ? getTrustGradeCompact(trustScore, {
          elite: tp("trustGradeElite"),
          official: tp("trustGradeOfficial"),
          alert: tp("trustGradeAlert"),
          yellow: tp("trustGradeYellow"),
        })
      : null;

  async function handleClaimStreak() {
    if (!canClaimStreak || claimingStreak) return;
    setClaimingStreak(true);
    try {
      const res = await fetch("/api/claim-daily-streak", { method: "POST" });
      const json = (await res.json()) as {
        ok: boolean;
        data?: { bonus: number };
        error?: string;
      };
      if (res.status === 429) {
        toast.error(tp("streakClaimRateLimit"));
        return;
      }
      if (!json.ok) {
        toast.error(json.error ?? tp("streakClaimAlreadyDone"));
        setStreakClaimed(true);
      } else {
        toast.success(
          tp("streakClaimSuccess", { bonus: json.data!.bonus, streak }),
        );
        track("daily_streak_claimed", {
          current_streak: streak,
          streak_freezes_owned: streakFreezesOwned,
          points_earned: json.data!.bonus,
        });
        setStreakClaimed(true);
      }
    } catch {
      toast.error(tp("streakClaimConnLost"));
    } finally {
      setClaimingStreak(false);
    }
  }

  if (compact) {
    return (
      <div className="mb-3 flex h-14 items-center gap-3 rounded-xl border border-white/8 bg-zinc-900/80 px-4">
        <div className="flex size-9 shrink-0 items-center justify-center rounded-full bg-zinc-800 text-lg">
          {avatar.startsWith("http") ? (
            <Image
              src={avatar}
              alt={username}
              width={36}
              height={36}
              className="size-9 rounded-full object-cover"
            />
          ) : (
            avatar
          )}
        </div>
        <div className="min-w-0 flex-1">
          <p className="truncate text-sm font-black text-white">{username}</p>
          <p className="text-[10px] font-bold text-zinc-500">
            {rank.emoji} {rank.label}
          </p>
        </div>
        <button
          type="button"
          onClick={() => setEditOpen(true)}
          className="flex size-8 shrink-0 items-center justify-center rounded-full bg-white/8 text-zinc-500 hover:text-white"
          aria-label={tp("editProfileAriaLabel")}
        >
          <Pencil className="size-3.5" />
        </button>
        {editOpen && (
          <ProfileEditModal
            onClose={() => setEditOpen(false)}
            initialUsername={username}
            initialAvatarUrl={avatarUrl}
            initialTeamId={team?.id ?? null}
            initialTeamName={team?.name ?? null}
            initialTeamLogo={team?.logo_url ?? null}
            initialPreferredCompetitions={preferredCompetitions}
            xp={xpTotal}
            onSaved={(data) => {
              setUsername(data.username);
              setAvatarUrl(data.avatar_url);
              setTeam(
                data.favorite_team_id
                  ? {
                      id: data.favorite_team_id,
                      name: data.team_name ?? "",
                      logo_url: data.team_logo,
                    }
                  : null,
              );
            }}
          />
        )}
      </div>
    );
  }

  const hasAutoUsername = isAutoGeneratedUsername(username);

  return (
    <>
      {hasAutoUsername && userEmail && showUsernameModal && (
        <UsernameSetupModal
          currentUsername={username}
          userEmail={userEmail}
          onDismiss={() => setShowUsernameModal(false)}
        />
      )}
      {hasAutoUsername && (
        <button
          type="button"
          onClick={() => setShowUsernameModal(true)}
          className="flex w-full items-center justify-between rounded-2xl border border-whistle/30 bg-whistle/10 px-4 py-3 text-left transition hover:bg-whistle/20 active:scale-[0.98]"
        >
          <div>
            <p className="text-sm font-black text-whistle">
              Personnalise ton pseudo
            </p>
            <p className="text-xs text-zinc-400">
              Ton pseudo actuel a été généré automatiquement : offre-toi quelque
              chose de mémorable
            </p>
          </div>
          <span className="ml-3 shrink-0 text-lg">✏️</span>
        </button>
      )}
      <div
        className="relative overflow-hidden rounded-2xl border border-white/8"
        style={{
          background: "linear-gradient(135deg, #064e3b 0%, #18181b 70%)",
        }}
      >
        <div
          className="pointer-events-none absolute -top-10 -left-10 size-40 rounded-full bg-emerald-500 opacity-20 blur-3xl"
          aria-hidden
        />
        <div
          className="pointer-events-none absolute -bottom-8 right-0 size-36 rounded-full bg-amber-500 opacity-15 blur-3xl"
          aria-hidden
        />

        <button
          type="button"
          onClick={() => setEditOpen(true)}
          className="absolute top-3 right-3 z-10 flex size-11 items-center justify-center rounded-full bg-white/10 text-white/70 transition hover:bg-white/20 hover:text-white active:scale-90"
          aria-label={tp("editProfileAriaLabel")}
        >
          <Pencil className="size-4" />
        </button>

        <div className="relative px-5 pt-5 pb-4">
          <div className="flex items-start gap-4">
            <div
              className={`flex size-20 shrink-0 items-center justify-center rounded-full bg-zinc-800 text-3xl ${ringCls}`}
            >
              {avatar.startsWith("http") ? (
                <Image
                  src={avatar}
                  alt={username}
                  width={80}
                  height={80}
                  className="size-20 rounded-full object-cover"
                />
              ) : (
                avatar
              )}
            </div>

            <div className="min-w-0 flex-1 pt-1">
              <p className="text-xl font-black text-white leading-tight">
                {username}
              </p>
              <span className="mt-1 inline-flex items-center gap-1 rounded-full border border-white/15 bg-white/8 px-2.5 py-0.5 text-[10px] font-black text-white/80">
                {rank.emoji} {rank.label}
              </span>
              {team && (
                <div className="mt-2 flex items-center gap-1.5">
                  {team.logo_url ? (
                    <Image
                      src={team.logo_url}
                      alt={team.name}
                      width={16}
                      height={16}
                      className="size-4 object-contain"
                    />
                  ) : (
                    <span className="text-xs">🏳️</span>
                  )}
                  <span className="text-[11px] font-bold text-white/60">
                    {team.name}
                  </span>
                </div>
              )}
            </div>
          </div>

          <div className="mt-4">
            <div className="mb-1 flex items-center justify-between">
              <span className="text-[9px] font-black uppercase tracking-widest text-white/40">
                XP · {xpInfo.level}
              </span>
              <span className="text-[9px] font-black tabular-nums text-white/40">
                {xpTotal.toLocaleString(bcp47)} /{" "}
                {xpInfo.next.toLocaleString(bcp47)}
              </span>
            </div>
            <div className="h-1 w-full overflow-hidden rounded-full bg-white/10">
              <div
                className="h-full rounded-full bg-emerald-400 transition-[width] duration-500"
                style={{ width: `${xpInfo.pct}%` }}
              />
            </div>
          </div>

          <div className="mt-4 flex items-center gap-2 flex-wrap">
            <div className="flex items-center gap-2 rounded-2xl border border-green-500/30 bg-green-500/10 px-4 py-2 shadow-[0_0_20px_rgba(34,197,94,0.3)]">
              <span className="text-2xl font-black tabular-nums text-green-400">
                {balance.toLocaleString(bcp47)}
              </span>
              <span className="text-[10px] font-black uppercase tracking-widest text-green-500/60">
                {tp("siffletsLabel")}
              </span>
            </div>

            {streak > 0 && (
              <button
                type="button"
                onClick={() => void handleClaimStreak()}
                disabled={!canClaimStreak || claimingStreak}
                className={`flex items-center gap-1.5 rounded-full px-3 py-2 text-[11px] font-black transition ${
                  canClaimStreak
                    ? "border border-orange-500/40 bg-orange-500/20 text-orange-400 hover:bg-orange-500/30"
                    : "border border-white/10 bg-zinc-800 text-zinc-500 cursor-default"
                }`}
              >
                🔥 {streak}
                {tp("streakDaysSuffix")}
                {canClaimStreak && ` +${50 * Math.min(streak, 7)}🪙`}
              </button>
            )}
            {streakFreezesOwned > 0 && (
              <span className="flex items-center gap-1 rounded-full border border-sky-500/30 bg-sky-500/10 px-3 py-2 text-[11px] font-black text-sky-400">
                🛡️ ×{streakFreezesOwned}
              </span>
            )}

            {trust && trustScore != null && (
              <span
                className={`flex items-center gap-1 rounded-full border px-2.5 py-1.5 text-[10px] font-black ${trust.color}`}
              >
                {trust.icon} {trust.label}
              </span>
            )}
          </div>
        </div>
      </div>

      {editOpen && (
        <ProfileEditModal
          onClose={() => setEditOpen(false)}
          initialUsername={username}
          initialAvatarUrl={avatarUrl}
          initialTeamId={team?.id ?? null}
          initialTeamName={team?.name ?? null}
          initialTeamLogo={team?.logo_url ?? null}
          xp={xpTotal}
          onSaved={(data) => {
            setUsername(data.username);
            setAvatarUrl(data.avatar_url);
            setTeam(
              data.favorite_team_id
                ? {
                    id: data.favorite_team_id,
                    name: data.team_name ?? "",
                    logo_url: data.team_logo,
                  }
                : null,
            );
          }}
        />
      )}
    </>
  );
}
