"use client";

import { useState, useEffect } from "react";
import { isAutoGeneratedUsername } from "@/lib/username";
import { UsernameSetupModal } from "./UsernameSetupModal";

const LS_KEY = "username_setup_dismissed";

export function UsernameSetupPrompt({
  username,
  userEmail,
}: {
  username: string;
  userEmail: string;
}) {
  const [show, setShow] = useState(false);

  useEffect(() => {
    if (isAutoGeneratedUsername(username) && !localStorage.getItem(LS_KEY)) {
      const id = setTimeout(() => setShow(true), 0);
      return () => clearTimeout(id);
    }
  }, [username]);

  if (!show) return null;

  return (
    <UsernameSetupModal
      currentUsername={username}
      userEmail={userEmail}
      onDismiss={() => setShow(false)}
    />
  );
}
